CREATE DATABASE oauth;

USE oauth;

CREATE TABLE users (
    Id int AUTO_INCREMENT,
    Username VARCHAR(255),
    Password TEXT NOT NULL,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated DATETIME ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN DEFAULT 1,
    CONSTRAINT PK_User PRIMARY KEY (Id, Username)
);

CREATE USER 'user' IDENTIFIED WITH mysql_native_password BY 'password';

GRANT DROP, CREATE, INSERT, UPDATE, DELETE, SELECT on users TO 'user';